title: MVIdeoGallery
description: Vision toolbox for video related tasks including action recognition, multi-object tracking, and robotic tasks.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
url: http://localhost:4000
baseurl: 
