title: AlphaVideo
description: Vision toolbox for video related tasks including action recognition, multi-object tracking.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
url: https://Alpha-Video.github.io/
baseurl: ''
